postgres:

  image: bitnami/postgresql
  container_name: postgres-db
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  volumes:
   - /var/lib/postgresql/data/

